# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elvis Dohmatob
email: gmdopp@gmail.com
description: mathematics / machine learning / convex optimization / game theory / brain science
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://amensch.fr" # the base hostname & protocol for your site
twitter_username: dohmatobelvis
github_username:  dohmatob

# Build settings
markdown: kramdown
exclude: [Makefile, upload.sh]

theme: jekyll-theme-leap-day


scholar:

  last_name: YOUR_LAST_NAME
  first_name: YOUR_FIRST_NAME

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

