# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arthur Mensch
email: arthur.mensch@m4x.org
description: Machine learning / Neuro-imaging / Data
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amensch.fr" # the base hostname & protocol for your site
twitter_username: arthurmensch
github_username:  arthurmensch

# Build settings
markdown: kramdown
exclude: [Makefile, upload.sh]
